export const CREATE_TOUR = 'CREATE_TOUR'
export const DELETE_TOUR = 'DELETE_TOUR'
export const UPDATE_TOUR = 'UPDATE_TOUR'
export const CREATE_STOP = 'CREATE_STOP'
export const DELETE_STOP = 'DELETE_STOP'
export const UPDATE_STOP = 'UPDATE_STOP'